### PR TITLE
Added random (not sure why Europa is complaining tho)

### PR DESCRIPTION
**Pull request by darkdarcool**
This adds random into the Europa math stdlib feature. It should have the following syntax:

```
var someRandomValue = random(minimum, maximum);
```

Not sure why it throws this error tho:

Screen Shot 2021-09-08 at 4 34 40 PM

Can some of the main devs help me?

### CODE REVIEW

**Comment by darkdarcool** [comment]
BTW: TESTS WILL BREAK FOR THIS PR BRANCH!

**Comment by cursorweb** [comment]
well yeah there's an arity did you forget to change that

**Comment by cursorweb** [comment]
also if you don't take the time to write commits i will not merge it.

**Comment by darkdarcool** [comment]
> well yeah there's an arity did you forget to change that

I took inspiration from the println, and it referenced rags as an array, so that’s what I took it as

**Comment by darkdarcool** [comment]
> also if you don't take the time to write commits i will not merge it.

Will take not of that in the future

**Comment by cursorweb** [comment]
lol nw its just important to say what you changed, making it easier to look at versions

anyways there's still a bug in europa on for loops reeeeeeee

**Comment by darkdarcool** [comment]
> lol nw its just important to say what you changed, making it easier to look at versions
> 
> anyways there's still a bug in europa on for loops reeeeeeee

Oooooof, hope you get it fixed

**Pull request closed without merging**
