### PR TITLE
Better repository

### PR DESCRIPTION
**Pull request by darkdarcool**
I added issue templates, and an examples dir, so it's easier to navigate and open issues!

### CODE REVIEW

**Comment by cursorweb** [comment]
It's all good except for examples, it looks like a repeat of what we already have -- tests

**Comment by keystove** [comment]
mm-hm

**Comment by 19wintersp** [comment]
Have you moved the tests to examples? Would that not nullify the tests which run the programs in there?

**Comment by darkdarcool** [comment]
A lot of languages repos have examples, so I thought to add it here, and to answer your criticism winter, the hello-world is one I also see, but you can edit it to be a more advanced hello world

**Comment by darkdarcool** [comment]
IK, but you can take out any example, add any example, and add a readme.md to the dir, with a disclaimer and whatnot.

**Comment by 19wintersp** [comment]
@darkdarcool You don't understand. You've broken the tests.

**Comment by darkdarcool** [comment]
I didn’t edit the code, and you can put som of the examples back, I can do it later

**Comment by 19wintersp** [comment]
@cursorweb You deleted the test programs directory, please just put them back

**Comment by cursorweb** [comment]
Oh yeah they are in the tests folder

**Pull request closed without merging**
